Repository bearhack-ucr/bearhack2024, pull requests merged in 2023-12, with the labels that each got.

#23 Get Involved Section
  jsconfig.json
  public/assets/book.svg
  public/assets/butterfly.svg
  public/assets/hat.svg
  src/components/static/GetInvolved.jsx
  src/components/static/HorizontalLine.jsx
  src/components/static/Link.jsx
  src/components/static/upcoming/Upcoming.jsx
Labels: frontend, page:landing, ready for review

#28 landing title page
  public/assets/title-bg.svg
  src/app/layout.js
  src/components/static/Countdown.jsx
  src/components/static/Link.jsx
  src/components/static/Title.jsx
  src/data/Config.js
  tailwind.config.js
Labels: page:landing, ready for review

#30 About us
  public/assets/frame.svg
  src/components/static/AboutUs.jsx
Labels: ready for review

#29 footer
  public/assets/footer.svg
  public/assets/logo.svg
  src/components/static/Footer.jsx
  src/data/static/Contacts.js
Labels: frontend, page:landing

#32 Meet the Team
  src/components/static/Team.jsx
  src/components/static/TeamMember.jsx
  src/components/static/Title.jsx
  src/data/static/TeamMembers.js
Labels: ready for review

#31 Form styling
  src/components/dynamic/Button.jsx
  src/components/dynamic/Checkbox.jsx
  src/components/dynamic/Input.jsx
  src/components/dynamic/Loading.jsx
  src/components/dynamic/ProtectedPage.jsx
  src/components/dynamic/Radio.jsx
  src/components/dynamic/Select.jsx
  src/components/dynamic/form/Form.jsx
  src/components/dynamic/form/Questions.jsx
  src/components/dynamic/form/Upload.jsx
  src/data/dynamic/Button.js
  tailwind.config.js
Labels: ready for review

#27 FAQ
  src/components/static/AboutUs.jsx
  src/components/static/FAQ.jsx
  src/components/static/ToggleSelection.jsx
  src/data/static/FAQ.js
Labels: page:landing, ready for review

#45 Fixes
  .github/workflows/pull-request.yaml
  README.md
  cypress.config.js
  package.json
  src/app/favicon.ico
  src/components/static/Title.jsx
  src/components/static/ToggleSelection.jsx
  src/components/static/live/Live.jsx
  src/data/Releases.js
  src/data/dynamic/form/Admins.js
  src/data/dynamic/form/Committees.js
  src/data/dynamic/form/Information.js
  src/data/dynamic/form/Interest.js
  src/data/dynamic/form/Judge.js
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Participant.js
  src/data/dynamic/form/Sponsors.js
  src/data/dynamic/form/Volunteers.js
Labels: ready for review
