Repository bearhack-ucr/bearhack2024, pull requests merged in 2024-04, with the labels that each got.

#126 changed dropdown colors
  package-lock.json
  src/components/dynamic/Select.jsx
Labels: bug

#130 Sync template
  src/app/engineering/hackathons/page.js
  src/app/manifest.js
  src/app/sitemap.js
  src/components/dynamic/Navigation.jsx
  src/components/dynamic/admin/dashboards/dashboard/Table.jsx
  src/components/dynamic/admin/services/calendar/CalendarWrapper.jsx
  src/components/dynamic/admin/services/calendar/Events.jsx
  src/components/dynamic/admin/services/calendar/Toolbar.jsx
  src/components/dynamic/form/form/Questions.jsx
  src/components/dynamic/user/Countdown.jsx
  src/components/dynamic/user/Dashboard.jsx
  src/components/dynamic/user/Hackpack.jsx
  src/components/dynamic/user/Hackpacks.jsx
  src/components/dynamic/user/Header.jsx
  src/components/dynamic/user/Judging.jsx
  src/components/dynamic/user/Packing.jsx
  src/components/dynamic/user/Rooms.jsx
  src/components/dynamic/user/Rules.jsx
  src/components/dynamic/user/Tile.jsx
  src/components/engineering/hackathons/Bearhack.jsx
  src/components/engineering/hackathons/Citrushack.jsx
  src/components/engineering/hackathons/Cutiehack.jsx
  src/components/engineering/hackathons/DesignVerse.jsx
  src/components/engineering/hackathons/Hackathons.jsx
  src/components/engineering/hackathons/Header.jsx
  src/components/engineering/hackathons/Rosehack.jsx
  src/components/static/Countdown.jsx
  src/components/static/Title.jsx
  src/data/Config.js
  src/data/dynamic/Navigation.js
  src/data/dynamic/admin/Calendar.js
  src/data/dynamic/admin/Icons.js
  src/data/dynamic/form/Admins.js
  src/data/dynamic/form/Committees.js
  src/data/dynamic/form/Feedback.js
  src/data/dynamic/form/Interest.js
  src/data/dynamic/form/Judge.js
  src/data/dynamic/form/Leads.js
  src/data/dynamic/form/Mentors.js
  src/data/dynamic/form/Panelists.js
  src/data/dynamic/form/Participant.js
  src/data/dynamic/form/Sponsors.js
  src/data/dynamic/form/Volunteers.js
  src/data/engineering/Navigation.js
Labels: ready for review

#129 skinned contacts
  src/components/admin/services/contacts/Contact.jsx
Labels: ready for review

#139 Sync template
  src/app/api/checkin/route.js
  src/app/api/dashboard/[type]/route.js
  src/app/api/dashboard/feedback/route.js
  src/app/api/dashboard/teams/route.js
  src/app/api/judging/route.js
  src/app/api/members/route.js
  src/app/api/participant/route.js
  src/app/api/statistics/route.js
  src/app/api/team/route.js
  src/app/error.js
  src/app/user/join/[teamID]/page.js
  src/components/Navigation.jsx
  src/components/engineering/Blog.jsx
  src/components/user/BulletPoints.jsx
  src/components/user/Collapse.jsx
  src/components/user/Countdown.jsx
  src/components/user/Dashboard.jsx
  src/components/user/Hackpack.jsx
  src/components/user/Hackpacks.jsx
  src/components/user/Judging.jsx
  src/components/user/Packing.jsx
  src/components/user/Rules.jsx
  src/data/Config.js
  src/data/user/Hackpacks.js
  src/data/user/Judging.jsx
  src/data/user/Rules.js
Labels: ready for review

#140 stanley/swirly
  public/bigswirly.svg
  public/dots.svg
  public/moredots.svg
  public/smallswirly.svg
  public/title-bg.svg
  src/components/Title.jsx
  tailwind.config.js
Labels: frontend/styling, page:landing

#138 Nova sagittarii/blog theme
  src/app/engineering/blog/[type]/page.js
  src/app/engineering/layout.js
Labels: ready for review

#141 Sponsors section
  public/acm.webp
  public/am2.webp
  public/bearhackGcap.webp
  public/bmesucr.webp
  public/gcap.webp
  public/numi.webp
  src/components/Sponsors.jsx
  src/components/Title.jsx
  src/components/live/Live.jsx
  src/data/Sponsors.js
Labels: frontend/styling, page:landing, ready for review

#142 added committee members
  src/components/Team.jsx
  src/data/TeamMembers.js
Labels: page:landing, ready for review

#145 fix team alignment again
  src/components/Team.jsx
Labels: bug, page:landing

#156 stanley/font
  src/components/engineering/Blog.jsx
Labels: ready for review

#160 Fix max width to delete scroll bar
  src/components/admin/services/checkin/CheckIn.jsx
Labels: bug, frontend/styling, page:dashboard, ready for review

#162 fix select text black on black
  src/components/Select.jsx
Labels: frontend/styling, ready for review

#165 Nova sagittarii/landing
  package-lock.json
  package.json
  src/components/AboutUs.jsx
  src/components/AboutUsText.jsx
  src/components/GetInvolved.jsx
  src/components/Title.jsx
  src/components/Tracks.jsx
  src/components/schedule/Events.jsx
  tailwind.config.js
Labels: frontend/styling, page:landing, ready for review

#173 Add judges
  public/judges/EthanRoos.webp
  public/judges/HalliePham.webp
  public/judges/JoshuaCandelaria.webp
  public/judges/KaranBhogal.webp
  public/judges/LisaChen.webp
  public/judges/RachitPrajapati.webp
  public/judges/RichYueh.webp
  public/judges/RohitManimaran.webp
  public/judges/SamarthSrinivasa.webp
  src/components/Judges.jsx
  src/components/Member.jsx
  src/components/live/Live.jsx
  src/components/postlive/Postlive.jsx
  src/components/schedule/Events.jsx
  src/data/Judges.js
Labels: frontend, page:landing, ready for review
